# usage: make lecture=xxx fmt=yyy typesize=zzz
#
# where lecture is the basename of one of the .tex files listed in
# main.tex, fmt is either "SLIDE" or "ARTICLE", and typesize is
# either "big" or "normal".

MYFLAGS := -P -C -E -traditional -DLECTURE=$(lecture)
TARGET = null
ifeq ($(fmt), slide)
  MAIN = s_$(lecture)
  TARGET = $(MAIN).dvi
  MYFLAGS := $(MYFLAGS) -DSLIDE
else
  MAIN = a_$(lecture)
  TARGET = $(MAIN).pdf
endif
ifeq ($(typesize), big)
  MYFLAGS := $(MYFLAGS) -DLargePrint
  MAIN := b$(MAIN)
endif

all : $(TARGET) dummy

$(MAIN).tex : main.tex $(lecture).tex
	echo "%DO NOT EDIT THIS FILE--SEE main.tex" > $@
	-cpp $(MYFLAGS) main.tex >> $@

$(MAIN).aux : $(MAIN).tex
	latex $(MAIN)

$(MAIN).bbl : $(MAIN).aux
	-bibtex $(MAIN)        

$(MAIN).pass2 : $(MAIN).aux $(MAIN).bbl
	latex $(MAIN)
	touch $@

$(MAIN).dvi : $(MAIN).pass2
	latex $(MAIN)

$(MAIN).pdf : $(MAIN).pass2
	pdflatex $(MAIN)

dummy :

null :
	echo "Must specify lecture on command line"

.PHONY : all dummy null
